### ISSUE TITLE
Document that composer doesn't work from web/

### ISSUE THREAD

**Issue by chx** [drupalcommerce/project-base#13]
Anyone sane would run `composer foo bar` from `web/` but no. That doesn't work and there are no sensible error messages either just a `Could not find package drupal/whatever`. It only works from the docroot.

**Comment by bojanz** [comment]
Which composer.json ended up in web/?
By default there is none there, which is why we didn't have the need to document it

**Comment by chx** [comment]
➜  web git:(schedule_c) ✗ cat composer.json
{
}

**Comment by webflo** [comment]
``composer require`` creates an empty composer.json

```
mkdir -p foobar
cd foobar
composer require some-random-package
cat composer.json
```

**Comment by bojanz** [comment]
That's the problem then.
We really need a way to detect Composer being run in the wrong directory. 
Beats me how though, since any plugin would run only if it was added to the root composer.json

**Comment by rachellawson** [comment]
The reason why composer.json is in the project root and not web root is that a project can contain dependencies that are not *just* drupal dependencies. As an example, both my current projects include drupalvm as a dependency.
Agreed that it would be really good if composer “looked up” for composer.json when executed deep in a folder structure. (An example of this type of behaviour working well would be vagrant). This would be something for the composer project, rather than this one, though, surely?

**Comment by bojanz** [comment]
Yes, but the problem remains, how to implement that logic without wrapping the Composer executable.

Makes me want to create a drupal-composer phar...

**Comment by rachellawson** [comment]
The problem exists across all composer-managed projects, whether drupal or not. I’ve been having a scroll through the issues on the composer project and can’t see an issue - maybe there should be one?

**Comment by bojanz** [comment]
Yeah, but most projects have all of their dependencies in vendor/ which is the "don't touch this" directory. Problems start only once you abandon that idea (like we have).

**Comment by rachellawson** [comment]
True - we have, though I’m pretty sure in all projects people are in a subfolder and think “Oh -I just need to add xxx”, use composer in that subfolder and then end up with weird random composer.json files that will never do anything. 

Okay, maybe it’s just me 😳

**Comment by thom8** [comment]
Having seperate composer projects inside a main project can be useful, for example I'll sometimes have a seperate tests project under `tests/` which will install all the test dependencies and not conflict with any project dependencies.

These can also be initialised from the main project in a `post-install` script.

**Comment by rachellawson** [comment]
So, ideally, composer should think “Is there a composer.json file in this folder? No? Is there one above? Use that.”

But that’s composer behaviour that needs to improve to cover that scenario of using it in the wrong folder.

**Comment by thom8** [comment]
but how would composer know if you're not actually wanting a new project inside a subdirectory?
composer should always be run in the project root, which might be a subdirectory of another project.

**Comment by bojanz** [comment]
Composer always assumes there is a root composer.json for your project.
Running Composer in a subdirectory is basically undefined behavior (thom8, your use case is handled via "require-dev" in the root file)

**Comment by thom8** [comment]
@bojanz `require-dev` is definitely preferred so I only use this in cases where I've found conflicts with test dependencies and the main project or the test team is seperate from the dev team.

**Comment by rachellawson** [comment]
@thom8 if you were wanting to start a new composer.json file, you would use `composer init`. If someone used `composer require`, it would be reasonable to go looking up for a composer.json

**Comment by thom8** [comment]
@rachellawson that might work but there's likely a bunch of other assumptions made that composer was run from the project root specifically with composer plugins.

Plugins I've made need assume this.

**Comment by rachellawson** [comment]
Just added this to composer...

https://github.com/composer/composer/issues/6426

**Comment by thom8** [comment]
Anyway, this is an upstream issue, currently composer is only designed is run in a project root.

Also, most of my scripts would break if this wasn't the case..

**Comment by chx** [comment]
Did anyone check what happens if we delete the empty composer.json from web/ and run it that way? Do we at least get an error? That's the problem, really: no usable errors. I am on mobile , can't test right now.

**Comment by mglaman** [comment]
It won't show any errors worthwhile. I've done this a few times. Only to
realize I needed to bump up a directory.

Auto generating a composer.json is neat. But I should suppose at least
asking to make one, to help catch wrong directory would be a good stsrt

**Comment by chx** [comment]
Oh yeah I see https://github.com/drupalcommerce/project-base/issues/13#issuecomment-302355915 webflo's comment. That'd be the bug.

**Comment by diqidoq** [comment]
Hm ... so I maybe found the home (here) of the issue I wanted to report? It has been discussed over there: https://www.drupal.org/node/2906637#comment-12260986

**Comment by bojanz** [comment]
Time to close this, the issue has been fixed in Composer. If you use Composer 1.5 it works from web/
