### ISSUE TITLE
index.php and other files are missing

### ISSUE THREAD

**Issue by ravimaniyar** [drupalcommerce/project-base#24]
I have followed the commands provided in the documentation and the skeleton of directories was created as expected with one complication. There were no files created on root.

The index.php, .htaccess and other files are missing. I have tried updating core but the files were not created. Any suggestions please?

**Comment by mglaman** [comment]
@ravimaniyar we'll have to see. I wonder if we need to update dependencies and resync with upstream project-base after 8.5.0

**Comment by bojanz** [comment]
We are in sync with project-base.

I just ran:
```
composer create-project drupalcommerce/project-base some-dir --stability dev --no-interaction
```
and I got a web/ folder with index.php and a .htaccess

**Comment by mglaman** [comment]
Confirmed, `drupal-composer/drupal-scaffold ` is doing it's job. @ravimaniyar you'll need to share your command output.

```
$ ls -l some-dir/web/
total 48
-rw-rw-rw-   1 mglaman  wheel   385 Mar 10 13:06 autoload.php
drwxr-xr-x  40 mglaman  wheel  1280 Mar 10 13:05 core
-rw-r--r--   1 mglaman  wheel   549 Mar 10 13:06 index.php
drwxr-xr-x   3 mglaman  wheel    96 Mar 10 13:05 modules
drwxr-xr-x   3 mglaman  wheel    96 Mar 10 13:05 profiles
-rw-r--r--   1 mglaman  wheel  1596 Mar 10 13:06 robots.txt
drwxr-xr-x   6 mglaman  wheel   192 Mar 10 13:06 sites
drwxr-xr-x   3 mglaman  wheel    96 Mar 10 13:06 themes
-rw-r--r--   1 mglaman  wheel   848 Mar 10 13:06 update.php
-rw-r--r--   1 mglaman  wheel  4555 Mar 10 13:06 web.config
```

**Comment by ravimaniyar** [comment]
Guys, after lot of digging I found that my php `memory_limit` parameter was being culprit. I increased it to 512M and this has worked properly. Thanks a lot.
