### ISSUE TITLE
Odd path for the profile

### ISSUE THREAD

**Issue by bojanz** [drupalcommerce/project-base#5]
web/profile ends up with:
commerce_base (empty)
contrib/commerce-base.

There should only be contrib/commerce_base (note the underscore instead of a dash)

**Comment by webflo** [comment]
I think you have to rename the package https://github.com/drupalcommerce/commerce_base/blob/8.x-1.x/composer.json#L2

**Comment by bojanz** [comment]
Thanks, fixed.
