### ISSUE TITLE
Use d.o. packagist instance instead of drupal-composer.org's

### ISSUE THREAD

**Issue by bradjones1** [drupalcommerce/project-base#7]
The drupal-composer.org packagist instance is deprecated in favor of the d.o. version. Should this be reflected here and in the main commerce repo re: inclusion in the repositories list as well as in the version numbers? As it stands, there's some manual acrobatics required to include commerce via composer into a project that's using the d.o. packagist.

Maintainers' thoughts?

**Comment by bradjones1** [comment]
Took a look through the issue queue for Drupal's packagist implementation and it looks  like there it some not-well-documented magic transformations happening on the composer.json files to accomodate for this at the moment... probably better to let that cook since I know bojanz has been  part of those talks from the issue credits.

**Comment by bojanz** [comment]
Now that the d.o endpoint is in beta, I'd be fine with switching to it here.

**Comment by weitzman** [comment]
I'm seeing a problem with the create-project for this project. See https://www.irccloud.com/pastebin/Mi2p9k0d/. Might be fixed by this issue.

**Comment by bojanz** [comment]
Could not reproduce. Definitely looks like a network issue. In any case, let's switch the endpoints ASAP.

**Comment by bojanz** [comment]
Done in b3bd566b9ce05a5f0346ca4f5ec70f97ad71b41a.
